---
title: "Dissemination"
output:
    html_document:
        css: style.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("features.R")
```

## Recorded Conference Talks and Webinars

```{r ConferenceFeatures, echo=FALSE}
feature(
    title="SeleniumConf 2018 - Selenium Grid Docker Containers, Selene and pytest",
    img="images/seleniumconf2018_logo.png",
    href="https://youtu.be/pUd9F_muBc4",
    desc="At SeleniumConf 2018, I introduced a setup based on the Selenium project's Selenium Grid Docker images, a Python library named Selene, and the pytest framework that is easy to maintain, version, upgrade, and distribute to members of your development team.<br/><br/>Watch it on YouTube: <a href='https://youtu.be/pUd9F_muBc4'>https://youtu.be/pUd9F_muBc4</a>"
)

feature(
    title="SGCI 2018 - Working in the R Ecosystem: Building Applications & Content for Your Gateway",
    img="images/sgci_webinar_201805_logo.png",
    href="https://sciencegateways.org/index.php?option=com_content&view=article&id=430:rstudio-open-source-solutions-for-gateways&catid=32:w",
    desc="For their May 2018 webinar, I spoke with the <a href='https://sciencegateways.org/home'>Science Gateways Community Institute (SGCI)</a> about how to use the <a href='https://shiny.rstudio.com/'>Shiny</a>, <a href='https://www.rplumber.io/'>Plumber</a>, and <a href='https://rmarkdown.rstudio.com/'>R Markdown</a> libraries to build static and dynamic, <a href='https://www.r-project.org/'>R</a> based, content that can be published on a science gateway. <br/><br/>SGCI Webinar Website: <a href='https://sciencegateways.org/index.php?option=com_content&view=article&id=430:rstudio-open-source-solutions-for-gateways&catid=32:w'>https://sciencegateways.org/index.php?option=com_content&view=article&id=430:rstudio-open-source-solutions-for-gateways&catid=32:w</a><br/>Watch it on YouTube: <a href='https://www.youtube.com/watch?v=8_N_EnXPv8k'>https://www.youtube.com/watch?v=8_N_EnXPv8k</a><br/>Examples, Links, Slides: <a href='https://github.com/dskard/sgci-201805'>https://github.com/dskard/sgci-201805</a>"
)

feature(
    title="SeleniumConf 2014 - Design Patterns Beyond the Page Object",
    img="images/seleniumconf2014_logo.png",
    href="https://www.youtube.com/watch?v=AVrnBJDQeaI",
    desc="At <a href='https://confengine.com/selenium-conf-2014'>SeleniumConf 2014</a>, their first year in India, I spoke about three design patterns you should be using once you understand the Page Object: WebForm Pattern, ItemList Pattern, and IframeWrap Pattern.<br/><br/>Watch it on YouTube: <a href='https://www.youtube.com/watch?v=AVrnBJDQeaI'>https://www.youtube.com/watch?v=AVrnBJDQeaI</a><br/>Download the slides: <a href='https://github.com/dskard/seleniumconf2014'>https://github.com/dskard/seleniumconf2014</a>"
)

```



## Workshop Materials

```{r WorkshopFeatures, echo=FALSE}
feature(
    title="PEARC 2017 - Interactive Science and Geospatial Visualization Tools for HUBzero Science Gateways",
    img="images/pearc17_logo.png",
    href="https://pearc17.sched.com/event/AQ3K/interactive-science-and-geospatial-visualization-tools-for-hubzero-science-gateways",
    desc="Tutorial at the Practice & Experience in Advanced Research Computing Conference about capabilities added to the <a href='https://hubzero.org'>HUBzero Platform</a> to support geospatial researchers. Collaborated with Kevin Wojkovich to develop presentation slides and a tutorial centered around building, running, and deploying R based applications (Shiny, R Markdown, RStudio IDE) on the HUB. Kevin presented the material and ran the tutorial.<br/><br/>Tutorial Instuctions: <a href='http://bit.ly/pearc17-hz3'>http://bit.ly/pearc17-hz3</a>",
    repo="https://github.com/dskard/pearc2017"
)

feature(
    title="Mozilla Festival 2016 - Build and Share a Scientific Simulation",
    img="images/mozfest2016_logo.png",
    href="http://bit.ly/mozfest415",
    desc="Research at the University level is filled with stories of code being passed down from grad student to grad student and referenced in papers but rarely being used by others outside of the original research team. In this workshop participants learned about what resources the <a href='https://hubzero.org'>HUBzero Platform</a> provides to help disseminate that research code, with a web or desktop style graphical user interface, to the world so it can be used by others and built upon in an Open Source ecosystem.<br/><br/>Workshop notes and presentations links: <s><a href='http://bit.ly/mozfest415'>http://bit.ly/mozfest415</a></s> (old link)"
)

feature(
    title="NCN Software Bootcamp",
    img="images/ncnsoftwarebootcamp_logo.png",
    href="https://github.com/dskard/ncnsoftwarebootcamp",
    desc="From 2007 to 2017, I helped run a software bootcamp sponsored by the <a href='https://nanohub.org/groups/ncn/'>Network for Computational Nanotechnology (NCN)</a>. The 3-5 day workshop was geared toward getting the summer students, participating in the <a href='https://engineering.purdue.edu/Engr/Research/SURF'>SURF</a> program, familiar with good programming practices, debugging skills, the <a href='http://rappture.org'>Rappture Toolkit</a>, source code repositories, and how to publish simulation tools on <a href='https://nanohub.org'>nanohub.org</a>. I've also run this workshop at <a href='http://illinois.edu/'>several</a> <a href='http://ucmerced.edu/'>other</a> <a href='https://www.nsu.edu/'>universities</a> and parts of it at <a href='https://hubzero.org/hubbub'>conferences</a>.<br/><br/>Workshop materials:<a href='https://github.com/dskard/ncnsoftwarebootcamp'>https://github.com/dskard/ncnsoftwarebootcamp</a>"
)

```

## Select Papers

<!--
* HUBzero and Pegasus: Integrating scientific workflows into science gateways - http://bit.ly/dk-pub-2014-1
-->

```{r PaperFeatures, echo=FALSE}
feature(
    title="HUBzero and Pegasus: Integrating scientific workflows into science gateways",
    img="images/hzpegasus2014_logo.png",
    href="http://bit.ly/dk-pub-2014-1",
    desc="Use the <a href='https://pegasus.isi.edu/'>Pegasus Workflow Management System</a> from within the HUBzero Platform tool containers, inside your simulation tool, or on the command line!<br/><br/>Read the paper: <a href='http://bit.ly/dk-pub-2014-1'>http://bit.ly/dk-pub-2014-1</a>"
)
```

## Other Content

<!--
* Caching Data with Pins Package - https://indyuser.github.io/IndyUserWebpg/2020/10/20/oct2020/
-->


```{r OtherFeatures, echo=FALSE}
feature(
    title="Quarto Experience",
    img="",
    href="https://github.com/dskard/indy-use-r-202208",
    desc="In this talk with Indy UseR, we hear about a first time experience using <a href='https://quarto.org/'>Quarto</a>, an open-source scientific and technical publishing system built on <a href='https://pandoc.org/'>Pandoc</a>. For this talk, I try using what I learned to write the presentation using Quarto.<br/><br/>Watch it on YouTube: <a href='https://www.youtube.com/watch?v=L25Iuw6z0Ik'>https://www.youtube.com/watch?v=L25Iuw6z0Ik</a>",
    repo="https://github.com/dskard/indy-use-r-202208"
)

feature(
    title="Caching Data with Pins Package",
    img="",
    href="https://indyuser.github.io/IndyUserWebpg/2020/10/20/oct2020/",
    desc="In this talk with Indy UseR, we explore the <a href='http://pins.rstudio.com/'>pins</a> package. The pins package allows users to save and retrieve data to and from “boards” that can be reused locally or shared with other when used with external services like Github, Kaggle, AWS S3, Google Cloud, Azure, Digital Ocean, or RStudio Connect. We take a look at the core functions of the pins package.<br/><br/>Watch it on YouTube: <a href='https://www.youtube.com/watch?v=qva4UmXk_u4'>https://www.youtube.com/watch?v=qva4UmXk_u4</a>",
    repo="https://github.com/dskard/indy-use-r-202010"
)

feature(
    title="renv: Usage Scenarios",
    img="",
    href="https://indyuser.github.io/IndyUserWebpg/2020/03/17/mar2020/",
    desc="In this talk with Indy UseR, we explore usage scenarios for <a href='https://rstudio.github.io/renv/'>renv</a>, an R package that helps create portable and reproducible development environments.<br/><br/>Watch it on YouTube: <a href='https://youtu.be/r6r6AdBMY2Y?t=1230'>https://youtu.be/r6r6AdBMY2Y?t=1230</a>",
    repo="https://github.com/dskard/indy-use-r-202003"
)

feature(
    title="Turning Your Analysis into an API with Plumber",
    img="",
    href="https://indyuser.github.io/IndyUserWebpg/2018/05/15/may2018/",
    desc="You’ve imported the data, cleaned it up, and built the model. Your next step is to communicate your findings with others. Typically this would mean writing a report or building a web application so other people could visualize how the model works, but sometime your Communicate step is someone else’s Import step. In this talk, we’ll explore how to expose your analysis to others in a programmatic way by using HTTP APIs built with the Plumber library. Our conversation will include a high level overview of how HTTP works, code based examples of building an API, and how to use that API from different programming languages.",
    repo="https://github.com/dskard/indy-use-r-201805"
)

feature(
    title="Docker, I've been meaning to …",
    img="",
    href="https://github.com/dskard/hl-tt-docker-201905",
    desc="It's something you've been meaning to look into, and every time you're ready to explore, something else comes up. That's life! Luckily, I have put together this quick primer presentation for the May 18, 2019 HackLafayette Thunder Talks that covers where Docker stands in the soup of virtualization setups out there, which commands you should probably know about to be productive, and an example of packaging up an application so it can be shared with others.<br/><br/>Examples, Links, Slides: <a href='https://github.com/dskard/hl-tt-docker-201905'>https://github.com/dskard/hl-tt-docker-201905</a>",
    repo="https://github.com/dskard/hl-tt-docker-201905"
)
```
