---
title: "Software"
output:
    html_document:
        css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("features.R")
```

## Libraries and Packages

```{r libraryFeatures, echo=FALSE}
feature(
    title="Rappture Toolkit",
    img="images/rappture_logo.png",
    href="http://rappture.org",
    desc="<b>R</b>apid <b>APP</b>lication infrastruc<b>TURE</b> toolkit that supports building desktop style graphical user interface for science based simulation tools and publishing them online.",
    codedin="C/C++, Tcl/Tk"
)

feature(
    title="HUBcheck",
    img="images/hubcheck_logo.png",
    href="https://github.com/codedsk/hubcheck",
    desc="A library for building automation and testing/checking scripts against the HUBzero Platform (website and tool container) that mimic the user experience.",
    codedin="Python"
)

feature(
    title="wrwroxy",
    img="images/wrwroxy_logo.png",
    href="https://github.com/codedsk/wrwroxy",
    desc="The <b>W</b>eber Re<b>W</b>rite p<b>ROXY</b> runs inside of the HUBzero Platform tool container, between the Exec Proxy and a web server based (weber) application, and forwards connections between the two, rewriting the header to remove the HUBzero specific parts of the request path. This allows the weber application to think it is serving files from the root of the web server. The proxy also has the capability of performing light security checks, like checking that incoming requests have the correct authentication cookie.",
    codedin="Python"
)

feature(
    title="invokeapp",
    img="images/invokeapp_logo.png",
    href="https://hubzero.org/documentation/2.1.0/tooldevs/invoke",
    desc="Script used to standardize the environment setup and launching of applications inside the HUBzero tool container.",
    dpkg="http://packages.hubzero.org/deb/pool/main/h/hubzero-invokeapp/hubzero-invokeapp_2.0.0.orig.tar.gz",
    codedin="Bash"
)


```

## Applications and Environments

```{r applicationFeatures, echo=FALSE}
feature(
    title="chuse",
    img="images/chuse_logo.png",
    href="http://packages.hubzero.org/deb/pool/main/h/hubzero-chuse/hubzero-chuse_2.0.0.orig.tar.gz",
    desc="Tcl/Tk based GUI wrapper around the HUBzero <i>use</i> utility for setting up environments inside the tool container.",
    dpkg="http://packages.hubzero.org/deb/pool/main/h/hubzero-chuse/hubzero-chuse_2.0.0.orig.tar.gz",
    codedin="Tcl/Tk"
)

feature(
    title="SolarPV",
    img="images/solarpv_logo.png",
    href="https://nanohub.org/resources/solarpv",
    desc="Rappture graphical user interface wrapping a Java based application that simulates electricity demand in residential communities with solar photovoltaic (PV) systems.",
    codedin="MySQL, Python, Bash"
)

feature(
    title="ParticleVE",
    img="images/particleve_logo.png",
    href="https://nanohub.org/resources/particleve",
    desc="Track and estimate particle velocities using video from the 2010 Deepwater Horizon oil spill in the Gulf of Mexico.",
    codedin="Tcl/Tk, C (libav/ffmpeg)"
)

feature(
    title="NanoFET",
    img="images/nanofet_logo.png",
    href="https://nanohub.org/resources/nanofet",
    desc="Simulates the effects of downscaling conventional CMOS devices, uncovering the challenges of working on the ever-shrinking nanoelectronics in today's devices.",
    codedin="FORTRAN, Rappture Toolkit, MPI"
)

feature(
    title="Workspace",
    img="images/workspace_logo.png",
    href="https://nanohub.org/resources/workspace",
    desc="A Linux desktop, in your web browser. Workspaces provide graphical access to your home directory on the HUB. They are packed with compilers, libraries, debuggers, your favorite text editor, and access to grid computing resources so you can perform research and develop code in a secure, containerized, persistant environment. I help setup, configure, and maintain workspaces on the HUBs managed by the HUBzero team.<br/><br/>Try it out for free by registering for an account on <a href=\"https://hubzero.org\">https://hubzero.org</a>."
)
```
